name: marlyse
favicon: null
layout_spectrum: 0.9915264095179737
typography_spectrum: 0.25094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#5d828b'
    - '#6a638c'
    - '#878656'
    - '#476766'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
