name: marlyse
favicon: null
layout_spectrum: 0.9915264095179737
typography_spectrum: 0.25094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d9d4'
    - '#b6aca0'
    - '#3d2e45'
    - '#996045'
    - '#590016'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
