name: marlyse
favicon: null
layout_spectrum: 0.9915264095179737
typography_spectrum: 0.25094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d5e9'
    - '#183948'
    - '#a0b6ce'
    - '#baba3d'
    - '#617744'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 1
purpose: []
