name: marlyse
favicon: null
layout_spectrum: 0.9915264095179737
typography_spectrum: 0.25094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00659d'
    - '#00202f'
    - '#f0f3f8'
    - '#744000'
    - '#dc8a0a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
